Parte 1: Introducción a las Librerías 

  Investiga la librería NumPy y explica cómo se realizan las siguientes operaciones con matrices:  
Multiplicación de matrices, Cálculo de la inversa de una matriz, Cálculo de valores propios y 
vectores propios de una matriz. Proporciona ejemplos de código en Python utilizando NumPy.

Para multiplicar dos matrices en NumPy, usamos la función np.dot() o el operador @. La multiplicación de matrices es posible si el número de columnas de la primera matriz coincide con el número de filas de la segunda.

In [3]:
import numpy as np

# Definicion de ambas matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
E = np.array([[1, 2, 3], [4, 5, 6]])
F = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

# Verificación de dimensiones
if A.shape[1] != B.shape[0]:
    print("El número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz")
else:
    # Multiplicación de matrices
    C = np.dot(A, B)

    # Alternativamente, podemos usar A @ B para la multiplicación de matrices
    D = A @ B

    print("Matriz C (A * B):")
    print(C)

# Verificación de dimensiones
if E.shape[1] != F.shape[0]:
    print("El número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz")
else:
    # Multiplicación de matrices

    G = np.dot(E, F)

    print("Matriz G (E * F):")
    print(G)


El número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz
Matriz G (E * F):
[[ 66  72  78]
 [156 171 186]]


Para calcular la inversa de una matriz cuadrada (matriz con el mismo número de filas y columnas), usamos np.linalg.inv(). Solo las matrices cuadradas no singulares (determinante distinto de cero) tienen inversa.

In [6]:
# Definimos una matriz cuadrada
A = np.array([[1, 2], [3, 4]])

# Calculamos la inversa
try:
    A_inv = np.linalg.inv(A)
    print("Inversa de A:")
    print(A_inv)
except np.linalg.LinAlgError:
    print("La matriz no es invertible")

# Definimos una matriz singular
B = np.array([[2, 4], [2, 4]])

# Intentamos calcular la inversa
try:
    B_inv = np.linalg.inv(B)
    print("Inversa de B:")
    print(B_inv)
except np.linalg.LinAlgError:
    print("La matriz no tiene inversa porque es singular. Su determinante es 0.")

Inversa de A:
[[-2.   1. ]
 [ 1.5 -0.5]]
La matriz no tiene inversa porque es singular.


NumPy permite calcular los valores propios y vectores propios de una matriz cuadrada mediante la función np.linalg.eig(). Esta función retorna dos valores: un array con los valores propios y una matriz donde cada columna representa un vector propio.

In [7]:
# Definimos una matriz cuadrada
A = np.array([[1, 2], [2, 3]])

# Calculamos valores y vectores propios
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Autovalores de A:")
print(eigenvalues)
print("Autovectores de A:")
print(eigenvectors)


Valores propios de A:
[-0.23606798  4.23606798]
Vectores propios de A:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


¿Cómo  utilizarías  NumPy  para  resolver  un  sistema  de  ecuaciones  lineales  utilizando  matrices    
Explica el proceso y proporciona un ejemplo en código?

Para resolver un sistema de ecuaciones lineales con NumPy, podemos usar el enfoque de matrices. Dado un sistema de ecuaciones de la forma:

A⋅X=B

donde:
𝐴 es la matriz de coeficientes,
𝑋 es el vector de incógnitas,
𝐵 es el vector de términos independientes,
podemos resolver el sistema utilizando la función np.linalg.solve(A, B), que encuentra 𝑋 aplicando álgebra lineal.
 
Proceso:
Definir la matriz de coeficientes (𝐴) y el vector de términos independientes (𝐵).
Utilizar np.linalg.solve(A, B) para obtener el vector solución (𝑋).

Supongamos el siguiente sistema de ecuaciones:
El sistema de ecuaciones lineales se puede escribir como:
 
\begin{cases} 
3x + 4y + 2z = 7 \\ 
2x - y + 3z = 4 \\ 
x + 2y - z = -1 
\end{cases} 


Este sistema se puede escribir en forma matricial como:


\begin{bmatrix} 
3 & 4 & 2 \\ 
2 & -1 & 3 \\ 
1 & 2 & -1 
\end{bmatrix} 

\begin{bmatrix} 
x \\ 
y \\ 
z 
\end{bmatrix} 
= 
\begin{bmatrix} 
7 \\ 
4 \\ 
-1 
\end{bmatrix} 


Donde:


A = 
\begin{bmatrix} 
3 & 4 & 2 \\ 
2 & -1 & 3 \\ 
1 & 2 & -1 
\end{bmatrix} 

 
B = 
\begin{bmatrix} 
7 \\ 
4 \\ 
-1 
\end{bmatrix} 


In [8]:
import numpy as np

# Matriz de coeficientes
A = np.array([[3, 4, 2], [2, -1, 3], [1, 2, -1]])

# Vector de términos independientes
B = np.array([7, 4, -1])

# Resolver el sistema de ecuaciones
X = np.linalg.solve(A, B)

print("Solución del sistema:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])


Solución del sistema:
x = -1.1333333333333337
y = 1.3333333333333335
z = 2.5333333333333337


¿Qué es SymPy y en qué áreas del cálculo diferencial se utiliza? Investiga cómo esta librería
facilita la resolución simbólica de ecuaciones diferenciales y qué ventajas tiene sobre métodos
puramente numéricos


**SymPy** es una biblioteca de Python para realizar cálculos simbólicos. A diferencia de otras bibliotecas numéricas (como NumPy, que trabaja principalmente con números y arreglos), SymPy permite manipular expresiones matemáticas de manera simbólica. Esto significa que puedes trabajar con ecuaciones, integrales, derivadas y otros elementos matemáticos en su forma algebraica y obtener soluciones exactas.

**Áreas del cálculo diferencial en las que se utiliza SymPy**

SymPy es especialmente útil en varias áreas del cálculo diferencial, tales como:

Derivación simbólica: Permite calcular derivadas de funciones de manera exacta.

Integración: Realiza integrales tanto definidas como indefinidas.

Series de Taylor y Fourier: Genera expansiones en series de funciones.

Solución de ecuaciones diferenciales: Resuelve ecuaciones diferenciales ordinarias (EDO) y ecuaciones diferenciales parciales (EDP) de forma simbólica.


**SymPy** ofrece una función llamada $$dsolve$$ para resolver ecuaciones diferenciales de forma simbólica. Esta función permite encontrar soluciones exactas para muchos tipos de ecuaciones diferenciales ordinarias, evitando las aproximaciones numéricas.

Consideremos la ecuación diferencial:

$$
𝑦
′
+
𝑦
=
𝑒^𝑥

$$

In [11]:
import sympy as sp

# Definir la variable independiente y la función
x = sp.symbols('x')
y = sp.Function('y')

# Definir la ecuación diferencial
edo = sp.Eq(y(x).diff(x) + y(x), sp.exp(x))

# Resolver la ecuación diferencial
solucion = sp.dsolve(edo, y(x))
print("Solución de la ecuación diferencial:")
sp.pprint(solucion)


Solución de la ecuación diferencial:
                 x
           -x   ℯ 
y(x) = C₁⋅ℯ   + ──
                2 
